import { useState } from 'react';
import { FileSignature, Bell, CheckCircle, XCircle, Clock, UserPlus, Calendar } from 'lucide-react';
import { joiningLetterRequests as initialRequests, JoiningLetterRequest } from '../../data/mockData';
import { Modal, Badge, Avatar, PrimaryButton, SecondaryButton, Card, SectionHeader, FormField, Select } from '../shared/UIComponents';
import { useApp } from '../../context/AppContext';

interface Props { isSuperAdmin: boolean; }

export default function JoiningLetterTab({ isSuperAdmin }: Props) {
  const { currentUser } = useApp();
  const [requests, setRequests] = useState<JoiningLetterRequest[]>(initialRequests);
  const [activeFilter, setActiveFilter] = useState<'all' | 'volunteer' | 'member' | 'new-member'>('all');
  const [selectedReq, setSelectedReq] = useState<JoiningLetterRequest | null>(null);
  const [showTenureModal, setShowTenureModal] = useState(false);
  const [tenure, setTenure] = useState('');
  const [tenureType, setTenureType] = useState('monthly');
  const [notification, setNotification] = useState<string | null>(null);

  const newMemberRequests = requests.filter(r => r.isNewMember && r.status === 'pending');

  const filtered = requests.filter(r => activeFilter === 'all' || r.type === activeFilter);

  const handleApprove = () => {
    if (!selectedReq) return;
    const adminName = currentUser?.name || 'Admin';

    // Check if it's new member and another admin already generated
    if (selectedReq.isNewMember) {
      const alreadyGenerated = requests.find(r => r.id === selectedReq.id && r.generatedBy);
      if (alreadyGenerated) {
        setNotification('Letter already generated by another admin.');
        setTimeout(() => setNotification(null), 3000);
        setSelectedReq(null);
        setShowTenureModal(false);
        return;
      }
    }

    setRequests(prev => prev.map(r => r.id === selectedReq.id
      ? { ...r, status: 'approved', generatedBy: adminName, tenure: tenure || r.tenure }
      : r
    ));
    setSelectedReq(null);
    setShowTenureModal(false);
    setTenure('');
  };

  const handleReject = (id: number) => {
    setRequests(prev => prev.map(r => r.id === id ? { ...r, status: 'rejected' } : r));
    setSelectedReq(null);
  };

  const pendingCount = requests.filter(r => r.status === 'pending').length;

  const tabs: { id: 'all' | 'volunteer' | 'member' | 'new-member'; label: string; count: number }[] = [
    { id: 'all', label: 'All Requests', count: requests.length },
    { id: 'volunteer', label: 'Volunteers', count: requests.filter(r => r.type === 'volunteer').length },
    { id: 'member', label: 'Members', count: requests.filter(r => r.type === 'member').length },
    { id: 'new-member', label: 'New Members', count: requests.filter(r => r.type === 'new-member').length },
  ];

  const monthlyOptions = Array.from({ length: 12 }, (_, i) => {
    const d = new Date(2025, i, 1);
    const label = d.toLocaleString('en-IN', { month: 'long', year: 'numeric' });
    return { label: `${label} (Monthly)`, value: `${label}` };
  });

  return (
    <div>
      {/* New Member Notification Banner */}
      {newMemberRequests.length > 0 && (
        <div className="mb-5 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl">
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-blue-500 rounded-xl flex items-center justify-center shrink-0">
              <Bell className="w-4 h-4 text-white" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold text-blue-800 dark:text-blue-300">New Member Applications</p>
              <p className="text-xs text-blue-600 dark:text-blue-400 mt-0.5">
                {newMemberRequests.length} pending application(s). Once any admin generates the letter, it will be locked for others.
              </p>
              <div className="flex flex-wrap gap-2 mt-2">
                {newMemberRequests.map(r => (
                  <span key={r.id} className="text-xs bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 px-2.5 py-1 rounded-full flex items-center gap-1">
                    <UserPlus className="w-3 h-3" /> {r.name}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {notification && (
        <div className="mb-4 p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700 rounded-xl text-sm text-amber-700 dark:text-amber-400">
          ⚠️ {notification}
        </div>
      )}

      <SectionHeader
        title="Joining Letters"
        subtitle={`${pendingCount} pending approval`}
      />

      {/* Filter Tabs */}
      <div className="flex gap-2 mb-5 overflow-x-auto pb-1">
        {tabs.map(tab => (
          <button key={tab.id} onClick={() => setActiveFilter(tab.id)}
            className={`px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${activeFilter === tab.id ? 'bg-blue-600 text-white shadow-sm' : 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:border-blue-300'}`}>
            {tab.label}
            <span className={`ml-2 px-1.5 py-0.5 rounded-full text-xs ${activeFilter === tab.id ? 'bg-blue-500 text-white' : 'bg-slate-100 dark:bg-slate-700 text-slate-500'}`}>{tab.count}</span>
          </button>
        ))}
      </div>

      {/* Requests List */}
      <div className="space-y-3">
        {filtered.map(req => {
          const isGeneratedByOther = req.generatedBy && req.generatedBy !== currentUser?.name;
          return (
            <Card key={req.id} className="p-4">
              <div className="flex items-start gap-3">
                <Avatar initials={req.name.split(' ').map(n => n[0]).join('')} size="md" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-medium text-slate-800 dark:text-slate-200">{req.name}</p>
                      <div className="flex items-center gap-2 mt-1 flex-wrap">
                        <Badge status={req.status} />
                        <span className={`text-xs px-2 py-0.5 rounded-full ${req.type === 'volunteer' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400' : req.type === 'member' ? 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400' : 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'}`}>
                          {req.type === 'new-member' ? 'New Member' : req.type.charAt(0).toUpperCase() + req.type.slice(1)}
                        </span>
                        {req.isNewMember && <span className="text-xs text-amber-600 dark:text-amber-400 flex items-center gap-0.5"><Bell className="w-3 h-3" /> Notification sent</span>}
                      </div>
                    </div>
                    <span className="text-xs text-slate-400 shrink-0">{req.requestDate}</span>
                  </div>

                  <div className="flex items-center gap-2 mt-2 text-xs text-slate-500 dark:text-slate-400">
                    <Calendar className="w-3 h-3" />
                    <span>Requested tenure: <span className="text-slate-700 dark:text-slate-300 font-medium">{req.tenure}</span></span>
                  </div>

                  {req.generatedBy && (
                    <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-1">
                      ✓ Letter generated by {req.generatedBy}
                      {isGeneratedByOther && ' (locked)'}
                    </p>
                  )}
                </div>
              </div>

              {req.status === 'pending' && !isGeneratedByOther && (
                <div className="flex gap-2 mt-3 pt-3 border-t border-slate-100 dark:border-slate-700">
                  <button
                    onClick={() => { setSelectedReq(req); setTenureType(req.type === 'member' ? 'annual' : 'monthly'); setShowTenureModal(true); }}
                    className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-medium transition-colors"
                  >
                    <FileSignature className="w-3.5 h-3.5" /> Generate Letter
                  </button>
                  <button
                    onClick={() => handleReject(req.id)}
                    className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg bg-red-50 dark:bg-red-900/20 hover:bg-red-100 text-red-600 dark:text-red-400 text-xs font-medium transition-colors"
                  >
                    <XCircle className="w-3.5 h-3.5" /> Reject
                  </button>
                </div>
              )}

              {req.status === 'approved' && (
                <div className="mt-2 flex items-center gap-1.5 text-xs text-emerald-600 dark:text-emerald-400">
                  <CheckCircle className="w-3.5 h-3.5" /> Approved
                </div>
              )}
              {req.status === 'rejected' && (
                <div className="mt-2 flex items-center gap-1.5 text-xs text-red-500">
                  <XCircle className="w-3.5 h-3.5" /> Rejected
                </div>
              )}
            </Card>
          );
        })}
      </div>

      {filtered.length === 0 && (
        <div className="flex flex-col items-center justify-center py-16">
          <FileSignature className="w-12 h-12 text-slate-300 dark:text-slate-600 mb-3" />
          <p className="text-slate-500 dark:text-slate-400">No joining letter requests</p>
        </div>
      )}

      {/* Tenure Selection Modal */}
      {showTenureModal && selectedReq && (
        <Modal title="Generate Joining Letter" onClose={() => { setShowTenureModal(false); setSelectedReq(null); }}>
          <div className="space-y-4">
            <div className="p-3 bg-slate-50 dark:bg-slate-700/50 rounded-xl">
              <p className="text-sm font-medium text-slate-800 dark:text-slate-200">{selectedReq.name}</p>
              <p className="text-xs text-slate-500 dark:text-slate-400 capitalize">{selectedReq.type === 'new-member' ? 'New Member' : selectedReq.type}</p>
            </div>

            <FormField label="Tenure Type">
              <Select
                value={tenureType}
                onChange={setTenureType}
                options={[
                  { label: `Monthly (Volunteer)`, value: 'monthly' },
                  { label: `Annual Year (Member)`, value: 'annual' },
                ]}
              />
            </FormField>

            {tenureType === 'monthly' ? (
              <FormField label="Select Month">
                <Select value={tenure} onChange={setTenure} options={[
                  { label: 'Select month...', value: '' },
                  ...monthlyOptions
                ]} />
              </FormField>
            ) : (
              <FormField label="Financial Year">
                <Select value={tenure} onChange={setTenure} options={[
                  { label: 'Select year...', value: '' },
                  { label: 'FY 2025-26', value: 'FY 2025-26' },
                  { label: 'FY 2026-27', value: 'FY 2026-27' },
                  { label: 'FY 2024-25', value: 'FY 2024-25' },
                ]} />
              </FormField>
            )}

            {selectedReq.isNewMember && (
              <div className="p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700 rounded-xl text-xs text-amber-700 dark:text-amber-400">
                <Bell className="w-3.5 h-3.5 inline mr-1.5" />
                Generating this letter will disable it for other admins and close the notification.
              </div>
            )}

            <div className="flex gap-2">
              <PrimaryButton onClick={handleApprove} className="flex-1 justify-center">
                <FileSignature className="w-4 h-4" /> Generate & Approve
              </PrimaryButton>
              <SecondaryButton onClick={() => { setShowTenureModal(false); setSelectedReq(null); }} className="flex-1 justify-center">Cancel</SecondaryButton>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
}
